import type { Metadata } from "next";
import "@/app/globals.css";
import Header from "@/app/components/common/header";
import Footer from "./components/common/footer";


export const metadata: Metadata = {
  title: "اپلیکین کنج - کتابخانه آنلاین",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body
        className={`antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
